# Generated by Django 2.0.6 on 2018-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_component', models.CharField(max_length=255)),
                ('original_text', models.TextField()),
                ('altered_text', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('reason', models.TextField()),
            ],
        ),
    ]
